name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Connect to device '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - aranet-cli
        - aranet-tui
        - aranet-core
        - aranet-store
        - aranet-service
        - Other
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Aranet Device
      description: Device model and firmware version (if applicable)
      placeholder: "e.g., Aranet4 17C3C (FW v1.4.19)"

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      placeholder: "e.g., macOS 14.2, Ubuntu 22.04"

  - type: input
    id: rust-version
    attributes:
      label: Rust Version
      description: Output of `rustc --version`
      placeholder: "e.g., rustc 1.90.0"

  - type: input
    id: aranet-version
    attributes:
      label: Aranet Version
      description: Output of `aranet --version` or crate version
      placeholder: "e.g., 0.1.8"

  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Output
      description: Any relevant logs or error messages
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem

